# Generated by Django 5.1.5 on 2026-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at_user_is_email_verified_user_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('provider', 'Provider'), ('both', 'Both'), ('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('dept_head', 'Department Head'), ('employee', 'Employee'), ('vendor_admin', 'Vendor Admin'), ('vendor_staff', 'Vendor Staff')], default='participant', max_length=20),
        ),
    ]
