# Generated by Django 5.1.5 on 2026-03-01 20:01

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('spots_total', models.PositiveIntegerField()),
                ('spots_remaining', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='experiences.experience')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(default=bookings.models.generate_booking_reference, editable=False, max_length=20, unique=True)),
                ('num_participants', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('participant_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled_by_participant', 'Cancelled by Participant'), ('cancelled_by_provider', 'Cancelled by Provider'), ('completed', 'Completed'), ('no_show', 'No Show'), ('refunded', 'Refunded')], default='pending', max_length=30)),
                ('special_requests', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='experiences.experience')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.timeslot')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['experience', 'start_datetime', 'is_active'], name='time_slots_experie_d9737d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['participant', 'status'], name='bookings_partici_eda157_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_booking_4d53ac_idx'),
        ),
    ]
