# Generated by Django 5.1.5 on 2026-03-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'booking_sequences',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Set when booked by an HR Manager on behalf of their organisation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='organizations.organisation'),
        ),
    ]
