# Generated by Django 5.1.5 on 2026-03-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_booked_by'),
        ('organizations', '0002_organisationinvite_target_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='booking',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='organizations.team'),
        ),
    ]
