# Generated by Django 5.1.5 on 2026-03-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_short_code_to_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='organisationinvite',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
